# Generated by Django 4.0.1 on 2022-02-13 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, null=True)),
                ('credits', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('building', models.CharField(max_length=40, null=True)),
                ('budget', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('sec_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('semester', models.CharField(max_length=10, null=True)),
                ('year', models.CharField(max_length=10, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stud_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('stud_name', models.CharField(max_length=50)),
                ('tot_cred', models.IntegerField(null=True)),
                ('dept_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.department')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=6, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.course')),
                ('sec_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.section')),
                ('semester', models.ManyToManyField(related_name='semes', to='Management.Section')),
                ('stud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.student')),
                ('year', models.ManyToManyField(related_name='yer', to='Management.Section')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('instrustor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('instrustor_name', models.CharField(max_length=50, null=True)),
                ('salary', models.IntegerField(null=True)),
                ('dept_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.department')),
            ],
        ),
        migrations.CreateModel(
            name='CourseInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.course')),
                ('instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.instructor')),
                ('sec_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.section')),
                ('semester', models.ManyToManyField(related_name='sem', to='Management.Section')),
                ('year', models.ManyToManyField(related_name='yr', to='Management.Section')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='dept_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.department'),
        ),
    ]
