# Generated by Django 4.0.1 on 2022-02-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='instrustor_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
