# Generated by Django 4.0.1 on 2022-02-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0003_remove_courseinstructor_semester_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('room_no', models.CharField(default='', max_length=10, primary_key=True, serialize=False)),
                ('class_buiding', models.CharField(max_length=25, null=True)),
                ('capacity', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('timeslot_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=20, null=True)),
                ('start_time', models.CharField(max_length=20, null=True)),
                ('end_time', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='section_buidling',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
