# Generated by Django 4.0.1 on 2022-02-14 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0004_classroom_timeslot_section_section_buidling'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='room_no',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Management.classroom'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classroom',
            name='room_no',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
