# Generated by Django 4.0.1 on 2022-02-14 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0005_section_room_no_alter_classroom_room_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='timeslot_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Management.timeslot'),
            preserve_default=False,
        ),
    ]
