# Generated by Django 4.0.1 on 2022-02-18 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0006_section_timeslot_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prereq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prereq_id', models.CharField(max_length=10, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.course')),
            ],
        ),
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.instructor')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.student')),
            ],
        ),
    ]
